volumes:
  postgres-data:

services:
  frontend:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend:/workspace/mangacomics/frontend:cached
    working_dir: /workspace/mangacomics/frontend