volumes:
  postgres-data:

services:
  backend:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    ports:
      - "8080:8080"
    volumes:
      - ../../:/workspace:cached
    working_dir: /workspace/backend
    depends_on:
      - db
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      