version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    container_name: mangacomics-app
    ports:
      - "8080:8080"
    volumes:
      - ./mangacomics:/workspace
    working_dir: /workspace
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data