volumes:
  postgres-data:

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../:/workspace/mangacomics:cached
    working_dir: /workspace/mangacomics
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      