version: '3.9'

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    ports:
      - "8080:8080"
    volumes:
      - ../:/workspace/${localWorkspaceFolderBasename}
    working_dir: /workspace/${localWorkspaceFolderBasename}
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: