volumes:
  postgres-data:

services:
  backend:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ../:/workspace/mangacomics/backend:cached
    working_dir: /workspace/mangacomics/backend
    depends_on:
      - db

  frontend:
    image: node:18-alpine
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ../:/workspace/mangacomics/frontend:cached
    working_dir: /workspace/mangacomics/frontend
    depends_on:
      - backend
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      